=== Brad-Christie-CI/sitecore-sif-snippets/schema/sif-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://sitecore.com/sif-schema.json",
  "title": "SitecoreInstallFramework-2.0.0",
  "type": "object",
  "properties": {
    "Modules": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "Parameters": {
      "type": "object",
      "patternProperties": {
        "^[a-zAA-Z]([a-zA-Z0-9:]+)?$": {
          "type": "object",
          "oneOf": [
            { "$ref": "#/definitions/parameter" }
          ]
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "Includes": {
      "type": "object",
      "patternProperties": {
        "^[a-zAA-Z]([a-zA-Z0-9:]+)?$": {
          "type": "object",
          "oneOf": [
            { "$ref": "#/definitions/include" }
          ]
        }
      }
    },
    "Register": {
      "properties": {
        "ConfigFunction": {
          "type": "object",
          "patternProperties": {
            "^[\\w]+$": {
              "type": "string",
              "pattern": "^[a-zA-Z][\\w-]*$"
            }
          },
          "additionalProperties": false
        },
        "Tasks": {
          "type": "object",
          "patternProperties": {
            "^[\\w]+$": {
              "type": "string",
              "pattern": "^[a-zA-Z][\\w-]*$"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "Tasks": {
      "patternProperties": {
        "^[a-zAA-Z]([a-zA-Z0-9:]+)?$": {
          "type": "object",
          "oneOf": [
            { "$ref": "#/definitions/task" }
          ]
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "UninstallTasks": {
      "patternProperties": {
        "^[a-zAA-Z]([a-zA-Z0-9:]+)?$": {
          "type": "object",
          "oneOf": [
            { "$ref": "#/definitions/task" }
          ]
        }
      },
      "additionalProperties": false
    },
    "Variables": {
      "type": "object",
      "patternProperties": {
        "^[\\w\\.-]+$": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    }
  },
  "additionalProperties": false,
  "required": ["Tasks"],
  "definitions": {
    "include": {
      "properties": {
        "Source": {
          "type": "string"
        }
      },
      "required": ["Source"]
    },
    "params": {
      "patternProperties": {
        "^[a-zA-Z][\\w-]*$": {
          "oneOf": [
            {
              "type": ["string","boolean","integer","number"]
            },
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ]
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "parameter": {
      "properties": {
        "Type": {
          "type": "string",
          "enum": ["string","char","byte","int","long","bool","decimal","single","double","datetime"]
        },
        "Description": {
          "type": "string"
        },
        "DefaultValue": {
          "type": ["string","boolean","integer","number"]
        },
        "Validation": {
          "type": "string",
          "examples": [
            "[ValidateNotNullOrEmpty($_)]",
            "[ValidateRange(1,255,$_)]"
          ]
        }
      },
      "required": ["Type"]
    },
    "task": {
      "properties": {
        "Params": {
          "type": ["object","array"],
          "oneOf": [
            { "$ref": "#/definitions/params" },
            {
              "type": "array",
              "items": {
                "type": "object",
                "oneOf": [
                  { "$ref": "#/definitions/params" }
                ]
              }
            }
          ]
        },
        "Requires": {
          "type": "string"
        },
        "Skip": {
          "type": ["boolean","string"],
          "oneOf": [
            { "type": "boolean" },
            { "type": "string" }
          ]
        },
        "Type": {
          "type": "string"
        }
      },
      "required": ["Type"]
    }
  }
}

=== Brad-Christie-CI/sitecore-sif-snippets/src/chrome/latest/chrome.json
{
  "Parameters": {
    "TempLocation": {
      "Type": "string",
      "Description": "Alternative location to save downloads. If left on the default $Env:Temp will be used.",
      "DefaultValue": "SIF-Default",
      "Validate": "[TestPath(variable('Temp.Location'))]"
    },
    "ChromeDownload": {
      "Type": "string",
      "Description": "Download location of chrome",
      "DefaultValue": "http://dl.google.com/chrome/install/latest/chrome_installer.exe"
    }
  },
  "Variables": {
    "Check.Chrome": "[ValidateNotNull(GetPackage(Name:variable('DisplayName.Chrome'),ErrorAction:'Continue'))]",

    "DisplayName.Chrome": "Google Chrome",

    "Chrome.SourceUri": "[parameter('ChromeDownload')]",
    "Chrome.Download": "[JoinPath(variable('Temp.Location'),'chrome.exe')]",

    "Temp.Location" : "[if(variable('Test.Temp.Location'),Environment('Temp'),parameter('TempLocation'))]",

    "Test.Temp.Location" : "[equal(parameter('TempLocation'),'SIF-Default')]"
  },
  "Register": {
    "ConfigFunction": {
      "GetPackage": "Get-Package",
      "TestPath": "Test-Path"
    },
    "Tasks": {
      "RemoveItem": "Remove-Item",
      "StartProcess": "Start-Process",
      "UninstallPackage": "Uninstall-Package"
    }
  },
  "Tasks": {
    "SetupTempLocation": {
      "Type": "EnsurePath",
      "Params": {
        "Exists": ["[variable('Temp.Location')]"]
      }
    },

    "DownloadChrome": {
      "Type": "DownloadFile",
      "Params": {
        "SourceUri": "[variable('Chrome.SourceUri')]",
        "DestinationPath": "[variable('Chrome.Download')]"
      },
      "Skip": "[or(variable('Check.Chrome'),TestPath(variable('Chrome.Download')))]"
    },
    "InstallChrome": {
      "Type": "StartProcess",
      "Params": {
        "FilePath": "[variable('Chrome.Download')]",
        "ArgumentList": ["/silent", "/install"],
        "Wait": true
      },
      "Skip": "[variable('Check.Chrome')]"
    },
    "CleanArtifacts": {
      "Type": "RemoveItem",
      "Params": {
        "LiteralPath": [
          "[variable('Chrome.Download')]"
        ],
        "Recurse": true,
        "ErrorAction": "SilentlyContinue"
      }
    }
  }
}

=== Brad-Christie-CI/sitecore-sif-snippets/src/dotnet-sdk/4.7.2/dotnet-sdk.json
{
  "Parameters": {
    "TempLocation": {
      "Type": "string",
      "Description": "Alternative location to save downloads. If left on the default $Env:Temp will be used.",
      "DefaultValue": "SIF-Default",
      "Validate": "[TestPath(variable('Temp.Location'))]"
    },
    "DotNetSdkDownload": {
      "Type": "string",
      "Description": "Download location for .NET Framework",
      "DefaultValue": "https://download.microsoft.com/download/3/B/F/3BFB9C35-405D-45DF-BDAF-0EB57D047888/NDP472-DevPack-ENU.exe"
    }
  },
  "Variables": {
    "Check.Is64": "[Eval('[System.Environment]::Is64BitOperatingSystem')]",
    "Check.DotNetSdk": "[ValidateNotNull(GetPackage(Name:variable('DisplayName.DotNetSdk'),ErrorAction:'Continue'))]",

    "DisplayName.DotNetSdk": "Microsoft .NET Framework 4.7.2 SDK",

    "DotNetSdk.SourceUri": "[parameter('DotNetSdkDownload')]",
    "DotNetSdk.Download": "[JoinPath(variable('Temp.Location'),'NDP472-DevPack-ENU.exe')]",

    "Temp.Location" : "[if(variable('Test.Temp.Location'),Environment('Temp'),parameter('TempLocation'))]",

    "Test.Temp.Location" : "[equal(parameter('TempLocation'),'SIF-Default')]"
  },
  "Register": {
    "ConfigFunction": {
      "Eval": "Invoke-Expression",
      "GetPackage": "Get-Package",
      "TestPath": "Test-Path"
    },
    "Tasks": {
      "RemoveItem": "Remove-Item",
      "StartProcess": "Start-Process",
      "UninstallPackage": "Uninstall-Package"
    }
  },
  "Tasks": {
    "SetupTempLocation": {
      "Type": "EnsurePath",
      "Params": {
        "Exists": ["[variable('Temp.Location')]"]
      }
    },

    "DownloadDotNetSdk": {
      "Type": "DownloadFile",
      "Params": {
        "SourceUri": "[variable('DotNetSdk.SourceUri')]",
        "DestinationPath": "[variable('DotNetSdk.Download')]"
      },
      "Skip": "[or(variable('Check.DotNetSdk'),TestPath(variable('DotNetSdk.Download')))]"
    },
    "InstallDotNetSdk": {
      "Type": "StartProcess",
      "Params": {
        "FilePath": "[variable('DotNetSdk.Download')]",
        "ArgumentList": ["/q", "/norestart"],
        "Wait": true
      },
      "Skip": "[variable('Check.DotNetSdk')]"
    },
    "CleanArtifacts": {
      "Type": "RemoveItem",
      "Params": {
        "LiteralPath": [
          "[variable('DotNetSdk.Download')]"
        ],
        "Recurse": true,
        "ErrorAction": "SilentlyContinue"
      }
    }
  }
}

=== Brad-Christie-CI/sitecore-sif-snippets/src/vcredist/2015/vcredist.json
{
  "Parameters": {
    "TempLocation": {
      "Type": "string",
      "Description": "Alternative location to save downloads. If left on the default $Env:Temp will be used.",
      "DefaultValue": "SIF-Default",
      "Validate": "[TestPath(variable('Temp.Location'))]"
    },
    "VCRedistDownload": {
      "Type": "string",
      "Description": "Download location for VC++ 2015 Redistributable (x86)",
      "DefaultValue": "https://download.microsoft.com/download/6/D/F/6DF3FF94-F7F9-4F0B-838C-A328D1A7D0EE/vc_redist.x86.exe"
    },
    "VCRedist64Download": {
      "Type": "string",
      "Description": "Download location for VC++ 2015 Redistributable (x64)",
      "DefaultValue": "https://download.microsoft.com/download/6/D/F/6DF3FF94-F7F9-4F0B-838C-A328D1A7D0EE/vc_redist.x64.exe"
    }
  },
  "Variables": {
    "Check.Is64": "[Eval('[System.Environment]::Is64BitOperatingSystem')]",
    "Check.VCRedist": "[ValidateNotNull(GetPackage(Name:variable('DisplayName.VCRedist'),ErrorAction:'Continue'))]",

    "DisplayName.VCRedist": "Microsoft Visual C++ 2015 Redistributable * - 14.0.24212",

    "VCRedist.SourceUri": "[if(variable('Check.Is64'),parameter('VCRedist64Download'),parameter('VCRedistDownload'))]",
    "VCRedist.Download": "[JoinPath(variable('Temp.Location'),'vc_redist.exe')]",
    
    "Temp.Location" : "[if(variable('Test.Temp.Location'),Environment('Temp'),parameter('TempLocation'))]",

    "Test.Temp.Location" : "[equal(parameter('TempLocation'),'SIF-Default')]"
  },
  "Register": {
    "ConfigFunction": {
      "Eval": "Invoke-Expression",
      "GetPackage": "Get-Package",
      "TestPath": "Test-Path"
    },
    "Tasks": {
      "RemoveItem": "Remove-Item",
      "StartProcess": "Start-Process"
    }
  },
  "Tasks": {
    "SetupTempLocation": {
      "Type": "EnsurePath",
      "Params": {
        "Exists": ["[variable('Temp.Location')]"]
      }
    },

    "DownloadVCRedist": {
      "Type": "DownloadFile",
      "Params": {
        "SourceUri": "[variable('VCRedist.SourceUri')]",
        "DestinationPath": "[variable('VCRedist.Download')]"
      },
      "Skip": "[or(variable('Check.VCRedist'),TestPath(variable('VCRedist.Download')))]"
    },
    "InstallVCRedist": {
      "Type": "StartProcess",
      "Params": {
        "FilePath": "[variable('VCRedist.Download')]",
        "ArgumentList": ["/quiet", "/passive", "/norestart"]
      },
      "Skip": "[variable('Check.VCRedist')]"
    },

    "CleanArtifacts": {
      "Type": "RemoveItem",
      "Params": {
        "LiteralPath": [
          "[variable('VCRedist.Download')]"
        ],
        "Recurse": true,
        "ErrorAction": "SilentlyContinue"
      }
    }
  }
}

=== Brad-Christie-CI/sitecore-sif-snippets/src/7zip/1806/7zip.json
{
  "Parameters": {
    "TempLocation": {
      "Type": "String",
      "Description": "Alternative location to save downloads. If left on the default $Env:Temp will be used.",
      "DefaultValue": "SIF-Default",
      "Validate": "[TestPath(variable('Temp.Location'))]"
    },
    "SevenZipDownload": {
      "Type": "String",
      "Description": "Download locations of 7-zip (x86)",
      "DefaultValue": "https://www.7-zip.org/a/7z1806.exe"
    },
    "SevenZip64Download": {
      "Type": "String",
      "Description": "Download locations of 7-zip (x64)",
      "DefaultValue": "https://www.7-zip.org/a/7z1806-x64.exe"
    }
  },
  "Variables": {
    "Check.Is64": "[Eval('[System.Environment]::Is64BitOperatingSystem')]",
    "Check.SevenZip": "[ValidateNotNull(GetPackage(Name:'7-Zip` *',ErrorAction:'Continue'))]",

    "SevenZip.SourceUri": "[if(variable('Check.Is64'),parameter('SevenZip64Download'),parameter('SevenZipDownload'))]",
    "SevenZip.Download": "[JoinPath(variable('Temp.Location'),'7z.exe')]",

    "Temp.Location" : "[if(variable('Test.Temp.Location'),Environment('Temp'),parameter('TempLocation'))]",

    "Test.Temp.Location" : "[equal(parameter('TempLocation'),'SIF-Default')]"
  },
  "Register": {
    "ConfigFunction": {
      "Eval": "Invoke-Expression",
      "GetPackage": "Get-Package",
      "TestPath": "Test-Path"
    },
    "Tasks": {
      "RemoveItem": "Remove-Item",
      "StartProcess": "Start-Process",
      "UninstallPackage": "Uninstall-Package"
    }
  },
  "Tasks": {
    "SetupTempLocation": {
      "Type": "EnsurePath",
      "Params": {
        "Exists": ["[variable('Temp.Location')]"]
      }
    },

    "DownloadSevenZip": {
      "Type": "DownloadFile",
      "Params": {
        "SourceUri": "[variable('SevenZip.SourceUri')]",
        "DestinationPath": "[variable('SevenZip.Download')]"
      },
      "Skip": "[or(variable('Check.SevenZip'),TestPath(variable('SevenZip.Download')))]"
    },
    "InstallSevenZip": {
      "Type": "StartProcess",
      "Params": {
        "FilePath": "[variable('SevenZip.Download')]",
        "ArgumentList": ["/S"],
        "Wait": true
      },
      "Skip": "[variable('Check.SevenZip')]"
    },
    "CleanArtifacts": {
      "Type": "RemoveItem",
      "Params": {
        "LiteralPath": [
          "[variable('SevenZip.Download')]"
        ],
        "Recurse": true,
        "ErrorAction": "SilentlyContinue"
      }
    }
  }
}
