=== Brad-Christie-CI/sitecore-sif-snippets/schema/sif-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://sitecore.com/sif-schema.json",
  "title": "SitecoreInstallFramework-2.0.0",
  "type": "object",
  "properties": {
    "Modules": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "Parameters": {
      "type": "object",
      "patternProperties": {
        "^[a-zAA-Z]([a-zA-Z0-9:]+)?$": {
          "type": "object",
          "oneOf": [
            { "$ref": "#/definitions/parameter" }
          ]
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "Includes": {
      "type": "object",
      "patternProperties": {
        "^[a-zAA-Z]([a-zA-Z0-9:]+)?$": {
          "type": "object",
          "oneOf": [
            { "$ref": "#/definitions/include" }
          ]
        }
      }
    },
    "Register": {
      "properties": {
        "ConfigFunction": {
          "type": "object",
          "patternProperties": {
            "^[\\w]+$": {
              "type": "string",
              "pattern": "^[a-zA-Z][\\w-]*$"
            }
          },
          "additionalProperties": false
        },
        "Tasks": {
          "type": "object",
          "patternProperties": {
            "^[\\w]+$": {
              "type": "string",
              "pattern": "^[a-zA-Z][\\w-]*$"
            }
          },
          "additionalProperties": false
        }
      }
    },
    "Tasks": {
      "patternProperties": {
        "^[a-zAA-Z]([a-zA-Z0-9:]+)?$": {
          "type": "object",
          "oneOf": [
            { "$ref": "#/definitions/task" }
          ]
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "UninstallTasks": {
      "patternProperties": {
        "^[a-zAA-Z]([a-zA-Z0-9:]+)?$": {
          "type": "object",
          "oneOf": [
            { "$ref": "#/definitions/task" }
          ]
        }
      },
      "additionalProperties": false
    },
    "Variables": {
      "type": "object",
      "patternProperties": {
        "^[\\w\\.-]+$": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    }
  },
  "additionalProperties": false,
  "required": ["Tasks"],
  "definitions": {
    "include": {
      "properties": {
        "Source": {
          "type": "string"
        }
      },
      "required": ["Source"]
    },
    "params": {
      "patternProperties": {
        "^[a-zA-Z][\\w-]*$": {
          "oneOf": [
            {
              "type": ["string","boolean","integer","number"]
            },
            {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ]
        }
      },
      "additionalProperties": false,
      "minProperties": 1
    },
    "parameter": {
      "properties": {
        "Type": {
          "type": "string",
          "enum": ["string","char","byte","int","long","bool","decimal","single","double","datetime"]
        },
        "Description": {
          "type": "string"
        },
        "DefaultValue": {
          "type": ["string","boolean","integer","number"]
        },
        "Validation": {
          "type": "string",
          "examples": [
            "[ValidateNotNullOrEmpty($_)]",
            "[ValidateRange(1,255,$_)]"
          ]
        }
      },
      "required": ["Type"]
    },
    "task": {
      "properties": {
        "Params": {
          "type": ["object","array"],
          "oneOf": [
            { "$ref": "#/definitions/params" },
            {
              "type": "array",
              "items": {
                "type": "object",
                "oneOf": [
                  { "$ref": "#/definitions/params" }
                ]
              }
            }
          ]
        },
        "Requires": {
          "type": "string"
        },
        "Skip": {
          "type": ["boolean","string"],
          "oneOf": [
            { "type": "boolean" },
            { "type": "string" }
          ]
        },
        "Type": {
          "type": "string"
        }
      },
      "required": ["Type"]
    }
  }
}

=== Brad-Christie-CI/sitecore-sif-snippets/src/nodejs/10.16.0/nodejs.json
{
  "Parameters": {
    "TempLocation": {
      "Type": "string",
      "Description": "Alternative location to save downloads. If left on the default $Env:Temp will be used.",
      "DefaultValue": "SIF-Default",
      "Validate": "[TestPath(variable('Temp.Location'))]"
    },
    "NodeJSDownload": {
      "Type": "string",
      "Description": "Download location of NodeJS.",
      "DefaultValue": "https://nodejs.org/dist/v10.16.0/node-v10.16.0-x86.msi"
    },
    "NodeJS64Download": {
      "Type": "string",
      "Description": "Download location of NodeJS.",
      "DefaultValue": "https://nodejs.org/dist/v10.16.0/node-v10.16.0-x64.msi"
    }
  },
  "Variables": {
    "Check.Is64": "[Eval('[System.Environment]::Is64BitOperatingSystem')]",
    "Check.NodeJS": "[ValidateNotNull(GetPackage(Name:variable('DisplayName.NodeJS'),ErrorAction:'Continue'))]",

    "DisplayName.NodeJS": "Node.js",

    "NodeJS.SourceUri": "[if(variable('Check.Is64'),parameter('NodeJS64Download'),parameter('NodeJSDownload'))]",
    "NodeJS.Download": "[JoinPath(variable('Temp.Location'),'nodejs.msi')]",

    "Temp.Location" : "[if(variable('Test.Temp.Location'),Environment('Temp'),parameter('TempLocation'))]",

    "Test.Temp.Location" : "[equal(parameter('TempLocation'),'SIF-Default')]"
  },
  "Register": {
    "ConfigFunction": {
      "Eval": "Invoke-Expression",
      "GetPackage": "Get-Package",
      "TestPath": "Test-Path"
    },
    "Tasks": {
      "RemoveItem": "Remove-Item",
      "StartProcess": "Start-Process",
      "UninstallPackage": "Uninstall-Package"
    }
  },
  "Tasks": {
    "SetupTempLocation": {
      "Type": "EnsurePath",
      "Params": {
        "Exists": ["[variable('Temp.Location')]"]
      }
    },

    "DownloadNodeJS": {
      "Type": "DownloadFile",
      "Params": {
        "SourceUri": "[variable('NodeJS.SourceUri')]",
        "DestinationPath": "[variable('NodeJS.Download')]"
      },
      "Skip": "[or(variable('Check.NodeJS'),TestPath(variable('NodeJS.Download')))]"
    },
    "InstallNodeJS": {
      "Type": "StartProcess",
      "Params": {
        "FilePath": "msiexec.exe",
        "ArgumentList": [
          "/i", "[variable('NodeJS.Download')]",
          "/quiet", "/norestart"
        ],
        "Wait": true
      },
      "Skip": "[variable('Check.NodeJS')]"
    },
    "UpdateNpm": {
      "Type": "StartProcess",
      "Params": {
        "FilePath": "npm.exe",
        "ArgumentList": ["install", "-g", "npm"],
        "Wait": true
      }
    },
    "CleanArtifacts": {
      "Type": "RemoveItem",
      "Params": {
        "LiteralPath": [
          "[variable('NodeJS.Download')]"
        ],
        "Recurse": true,
        "ErrorAction": "SilentlyContinue"
      }
    }
  }
}

=== Brad-Christie-CI/sitecore-sif-snippets/src/dotnet-hosting/2.1.7/dotnet-hosting.json
{
  "Parameters": {
    "TempLocation": {
      "Type": "string",
      "Description": "Alternative location to save downloads. If left on the default $Env:Temp will be used.",
      "DefaultValue": "SIF-Default",
      "Validate": "[TestPath(variable('Temp.Location'))]"
    },
    "DotNetHostingDownload": {
      "Type": "string",
      "Description": "Download location for .NET Core Runtime & Hosting Bundle",
      "DefaultValue": "https://download.visualstudio.microsoft.com/download/pr/eebd54bc-c3a2-4580-bb29-b35c1c5ffa92/22ffe5649861167d3d5728d3cb4b10a1/dotnet-hosting-2.1.12-win.exe"
    }
  },
  "Variables": {
    "Check.DotNetHosting": "[ValidateNotNull(GetPackage(Name:variable('DisplayName.DotNetHosting'),ErrorAction:'Continue'))]",

    "DisplayName.DotNetHosting": "Microsoft .NET Core 2.1.12 - Windows Server Hosting",

    "DotNetHosting.SourceUri": "[parameter('DotNetHostingDownload')]",
    "DotNetHosting.Download": "[JoinPath(variable('Temp.Location'),'dotnet-hosting-2.1.12-win.exe')]",

    "Temp.Location" : "[if(variable('Test.Temp.Location'),Environment('Temp'),parameter('TempLocation'))]",

    "Test.Temp.Location" : "[equal(parameter('TempLocation'),'SIF-Default')]"
  },
  "Register": {
    "ConfigFunction": {
      "Eval": "Invoke-Expression",
      "GetPackage": "Get-Package",
      "TestPath": "Test-Path"
    },
    "Tasks": {
      "RemoveItem": "Remove-Item",
      "StartProcess": "Start-Process",
      "UninstallPackage": "Uninstall-Package"
    }
  },
  "Tasks": {
    "SetupTempLocation": {
      "Type": "EnsurePath",
      "Params": {
        "Exists": ["[variable('Temp.Location')]"]
      }
    },

    "DownloadDotNetHosting": {
      "Type": "DownloadFile",
      "Params": {
        "SourceUri": "[variable('DotNetHosting.SourceUri')]",
        "DestinationPath": "[variable('DotNetHosting.Download')]"
      },
      "Skip": "[or(variable('Check.DotNetHosting'),TestPath(variable('DotNetHosting.Download')))]"
    },
    "InstallDotNetHosting": {
      "Type": "StartProcess",
      "Params": {
        "FilePath": "[variable('DotNetHosting.Download')]",
        "ArgumentList": ["/install", "/quiet"],
        "Wait": true
      },
      "Skip": "[variable('Check.DotNetHosting')]"
    },
    "CleanArtifacts": {
      "Type": "RemoveItem",
      "Params": {
        "LiteralPath": [
          "[variable('DotNetHosting.Download')]"
        ],
        "Recurse": true,
        "ErrorAction": "SilentlyContinue"
      }
    }
  }
}

=== Brad-Christie-CI/sitecore-sif-snippets/src/git/2.22.0/git.json
{
  "Parameters": {
    "TempLocation": {
      "Type": "string",
      "Description": "Alternative location to save downloads. If left on the default $Env:Temp will be used.",
      "DefaultValue": "SIF-Default",
      "Validate": "[TestPath(variable('Temp.Location'))]"
    },
    "GitDownload": {
      "Type": "string",
      "Description": "Download locations of Git for Windows (x86)",
      "DefaultValue": "https://github.com/git-for-windows/git/releases/download/v2.22.0.windows.1/Git-2.22.0-32-bit.exe"
    },
    "Git64Download": {
      "Type": "string",
      "Description": "Download locations of Git for Windows (x64)",
      "DefaultValue": "https://github.com/git-for-windows/git/releases/download/v2.22.0.windows.1/Git-2.22.0-64-bit.exe"
    }
  },
  "Variables": {
    "Check.Is64": "[Eval('[System.Environment]::Is64BitOperatingSystem')]",
    "Check.Git": "[ValidateNotNull(GetPackage(Name:'Git` version` *',ErrorAction:'Continue'))]",

    "Git.SourceUri": "[if(variable('Check.Is64'),parameter('Git64Download'),parameter('GitDownload'))]",
    "Git.Download": "[JoinPath(variable('Temp.Location'),'git.exe')]",

    "Temp.Location" : "[if(variable('Test.Temp.Location'),Environment('Temp'),parameter('TempLocation'))]",

    "Test.Temp.Location" : "[equal(parameter('TempLocation'),'SIF-Default')]"
  },
  "Register": {
    "ConfigFunction": {
      "Eval": "Invoke-Expression",
      "GetPackage": "Get-Package",
      "TestPath": "Test-Path"
    },
    "Tasks": {
      "RemoveItem": "Remove-Item",
      "StartProcess": "Start-Process",
      "UninstallPackage": "Uninstall-Package"
    }
  },
  "Tasks": {
    "SetupTempLocation": {
      "Type": "EnsurePath",
      "Params": {
        "Exists": ["[variable('Temp.Location')]"]
      }
    },

    "DownloadGit": {
      "Type": "DownloadFile",
      "Params": {
        "SourceUri": "[variable('Git.SourceUri')]",
        "DestinationPath": "[variable('Git.Download')]"
      },
      "Skip": "[or(variable('Check.Git'),TestPath(variable('Git.Download')))]"
    },
    "InstallGit": {
      "Type": "StartProcess",
      "Params": {
        "FilePath": "[variable('Git.Download')]",
        "ArgumentList": [
          "/VERYSILENT",
          "/SUPPRESSMSGBOXES",
          "/NORESTART",
          "/NOCANCEL",
          "/SP-",
          "/LOG"
        ],
        "Wait": true
      },
      "Skip": "[variable('Check.Git')]"
    },
    "CleanArtifacts": {
      "Type": "RemoveItem",
      "Params": {
        "LiteralPath": [
          "[variable('Git.Download')]"
        ],
        "Recurse": true,
        "ErrorAction": "SilentlyContinue"
      }
    }
  }
}

=== Brad-Christie-CI/sitecore-sif-snippets/src/dotnet-sdk/4.7.1/dotnet-sdk.json
{
  "Parameters": {
    "TempLocation": {
      "Type": "string",
      "Description": "Alternative location to save downloads. If left on the default $Env:Temp will be used.",
      "DefaultValue": "SIF-Default",
      "Validate": "[TestPath(variable('Temp.Location'))]"
    },
    "DotNetDownload": {
      "Type": "string",
      "Description": "Download location for .NET Framework",
      "DefaultValue": "https://download.microsoft.com/download/9/0/1/901B684B-659E-4CBD-BEC8-B3F06967C2E7/NDP471-DevPack-ENU.exe"
    }
  },
  "Variables": {
    "Check.Is64": "[Eval('[System.Environment]::Is64BitOperatingSystem')]",
    "Check.DotNet": "[ValidateNotNull(GetPackage(Name:'Microsoft` .NET` Framework 4.7.1` SDK',ErrorAction:'Continue'))]",

    "DotNet.SourceUri": "[parameter('DotNetDownload')]",
    "DotNet.Download": "[JoinPath(variable('Temp.Location'),'NDP471-DevPack-ENU.exe')]",

    "Temp.Location" : "[if(variable('Test.Temp.Location'),Environment('Temp'),parameter('TempLocation'))]",

    "Test.Temp.Location" : "[equal(parameter('TempLocation'),'SIF-Default')]"
  },
  "Register": {
    "ConfigFunction": {
      "Eval": "Invoke-Expression",
      "GetPackage": "Get-Package",
      "TestPath": "Test-Path"
    },
    "Tasks": {
      "RemoveItem": "Remove-Item",
      "StartProcess": "Start-Process",
      "UninstallPackage": "Uninstall-Package"
    }
  },
  "Tasks": {
    "SetupTempLocation": {
      "Type": "EnsurePath",
      "Params": {
        "Exists": ["[variable('Temp.Location')]"]
      }
    },

    "DownloadDotNet": {
      "Type": "DownloadFile",
      "Params": {
        "SourceUri": "[variable('DotNet.SourceUri')]",
        "DestinationPath": "[variable('DotNet.Download')]"
      },
      "Skip": "[or(variable('Check.DotNet'),TestPath(variable('DotNet.Download')))]"
    },
    "InstallDotNet": {
      "Type": "StartProcess",
      "Params": {
        "FilePath": "[variable('DotNet.Download')]",
        "ArgumentList": ["/q", "/norestart"],
        "Wait": true
      },
      "Skip": "[variable('Check.DotNet')]"
    },
    "CleanArtifacts": {
      "Type": "RemoveItem",
      "Params": {
        "LiteralPath": [
          "[variable('DotNet.Download')]"
        ],
        "Recurse": true,
        "ErrorAction": "SilentlyContinue"
      }
    }
  }
}

=== Brad-Christie-CI/sitecore-sif-snippets/test/test-is64.json
{
  "Parameters":{},
  "Variables": {
    "Check.Is64": "[Eval('[System.Environment]::Is64BitOperatingSystem')]"
  },
  "Register": {
    "ConfigFunction": {
      "Eval": "Invoke-Expression"
    },
    "Tasks": {
      "WriteInformation": "Write-Information"
    }
  },
  "Tasks": {
    "CheckValue": {
      "Type": "WriteInformation",
      "Params": {
        "MessageData": "[variable('Check.Is64')]"
      }
    },
    "Is32Bit": {
      "Type": "WriteInformation",
      "Params": {
        "MessageData": "This is a 32-bit OS"
      },
      "Skip": "[variable('Check.Is64')]"
    },
    "Is64Bit": {
      "Type": "WriteInformation",
      "Params": {
        "MessageData": "This is a 64-bit OS"
      },
      "Skip": "[not(variable('Check.Is64'))]"
    }
  }
}

=== Brad-Christie-CI/sitecore-sif-snippets/src/git.json
{
  "Parameters": {
    "TempLocation": {
      "Type": "String",
      "Description": "Alternative location to save downloads. If left on the default $Env:Temp will be used.",
      "DefaultValue": "SIF-Default",
      "Validate": "[TestPath(variable('Temp.Location'))]"
    },
    "GitDownload": {
      "Type": "String",
      "Description": "Download locations of Git for Windows",
      "DefaultValue": "https://github.com/git-for-windows/git/releases/download/v2.20.1.windows.1/Git-2.20.1-64-bit.exe"
    }
  },
  "Variables": {
    "Check.Git": "[ValidateNotNull(GetPackage(Name:'Git` version` *',ErrorAction:'Continue'))]",

    "Git.Download": "[JoinPath(variable('Temp.Location'),'git.exe')]",

    "Temp.Location" : "[if(variable('Test.Temp.Location'),Environment('Temp'),parameter('TempLocation'))]",

    "Test.Temp.Location" : "[equal(parameter('TempLocation'),'SIF-Default')]"
  },
  "Register": {
    "ConfigFunction": {
      "GetPackage": "Get-Package",
      "TestPath": "Test-Path"
    },
    "Tasks": {
      "RemoveItem": "Remove-Item",
      "StartProcess": "Start-Process",
      "UninstallPackage": "Uninstall-Package"
    }
  },
  "Tasks": {
    "SetupTempLocation": {
      "Type": "EnsurePath",
      "Params": {
        "Exists": ["[variable('Temp.Location')]"]
      }
    },

    "DownloadGit": {
      "Type": "DownloadFile",
      "Params": {
        "SourceUri": "[parameter('GitDownload')]",
        "DestinationPath": "[variable('Git.Download')]"
      },
      "Skip": "[or(variable('Check.Git'),TestPath(variable('Git.Download')))]"
    },
    "InstallGit": {
      "Type": "StartProcess",
      "Params": {
        "FilePath": "[variable('Git.Download')]",
        "ArgumentList": [
          "/VERYSILENT",
          "/SUPPRESSMSGBOXES",
          "/NORESTART",
          "/NOCANCEL",
          "/SP-",
          "/LOG"
        ],
        "Wait": true
      },
      "Skip": "[variable('Check.Git')]"
    },
    "CleanArtifacts": {
      "Type": "RemoveItem",
      "Params": {
        "LiteralPath": [
          "[variable('Git.Download')]"
        ],
        "Recurse": true,
        "ErrorAction": "SilentlyContinue"
      }
    }
  }
}

=== Brad-Christie-CI/sitecore-sif-snippets/src/webdeploy/3.6/webdeploy.json
{
  "Parameters": {
    "TempLocation": {
      "Type": "string",
      "Description": "Alternative location to save downloads. If left on the default $Env:Temp will be used.",
      "DefaultValue": "SIF-Default",
      "Validate": "[TestPath(variable('Temp.Location'))]"
    },
    "WebDeployDownload": {
      "Type": "string",
      "Description": "Download location for Web Deploy Module (x86)",
      "DefaultValue": "http://download.microsoft.com/download/0/1/D/01DC28EA-638C-4A22-A57B-4CEF97755C6C/WebDeploy_x86_en-US.msi"
    },
    "WebDeploy64Download": {
      "Type": "string",
      "Description": "Download location for Web Deploy Module (x64)",
      "DefaultValue": "http://download.microsoft.com/download/0/1/D/01DC28EA-638C-4A22-A57B-4CEF97755C6C/WebDeploy_amd64_en-US.msi"
    }
  },
  "Variables": {
    "Check.Is64": "[Eval('[System.Environment]::Is64BitOperatingSystem')]",
    "Check.WebDeploy": "[ValidateNotNull(GetPackage(Name:'Microsoft` Web` Deploy` *',ErrorAction:'Continue'))]",

    "WebDeploy.SourceUri": "[if(variable('Check.Is64'),parameter('WebDeploy64Download'),parameter('WebDeployDownload'))]",
    "WebDeploy.Download": "[JoinPath(variable('Temp.Location'),'rewrite.msi')]",

    "Temp.Location" : "[if(variable('Test.Temp.Location'),Environment('Temp'),parameter('TempLocation'))]",

    "Test.Temp.Location" : "[equal(parameter('TempLocation'),'SIF-Default')]"
  },
  "Register": {
    "ConfigFunction": {
      "Eval": "Invoke-Expression",
      "GetPackage": "Get-Package",
      "TestPath": "Test-Path"
    },
    "Tasks": {
      "RemoveItem": "Remove-Item",
      "StartProcess": "Start-Process",
      "UninstallPackage": "Uninstall-Package"
    }
  },
  "Tasks": {
    "SetupTempLocation": {
      "Type": "EnsurePath",
      "Params": {
        "Exists": ["[variable('Temp.Location')]"]
      }
    },

    "DownloadWebDeploy": {
      "Type": "DownloadFile",
      "Params": {
        "SourceUri": "[variable('WebDeploy.SourceUri')]",
        "DestinationPath": "[variable('WebDeploy.Download')]"
      },
      "Skip": "[or(variable('Check.WebDeploy'),TestPath(variable('WebDeploy.Download')))]"
    },
    "InstallWebDeploy": {
      "Type": "StartProcess",
      "Params": {
        "FilePath": "msiexec.exe",
        "ArgumentList": [
          "/i", "[variable('WebDeploy.Download')]",
          "/quiet", "/norestart"
        ],
        "Wait": true
      },
      "Skip": "[variable('Check.WebDeploy')]"
    },
    "CleanArtifacts": {
      "Type": "RemoveItem",
      "Params": {
        "LiteralPath": [
          "[variable('WebDeploy.Download')]"
        ],
        "Recurse": true,
        "ErrorAction": "SilentlyContinue"
      }
    }
  }
}

=== Brad-Christie-CI/sitecore-sif-snippets/src/dotnet/4.7.2/dotnet.json
{
  "Parameters": {
    "TempLocation": {
      "Type": "string",
      "Description": "Alternative location to save downloads. If left on the default $Env:Temp will be used.",
      "DefaultValue": "SIF-Default",
      "Validate": "[TestPath(variable('Temp.Location'))]"
    },
    "DotNetDownload": {
      "Type": "string",
      "Description": "Download location for .NET Framework",
      "DefaultValue": "https://download.microsoft.com/download/6/E/4/6E48E8AB-DC00-419E-9704-06DD46E5F81D/NDP472-KB4054530-x86-x64-AllOS-ENU.exe"
    }
  },
  "Variables": {
    "Check.Is64": "[Eval('[System.Environment]::Is64BitOperatingSystem')]",
    "Check.DotNet": "[ValidateNotNull(GetPackage(Name:variable('DisplayName.DotNet'),ErrorAction:'Continue'))]",
    
    "DisplayName.DotNet": "Microsoft .NET Framework 4.7.2 Targeting Pack",

    "DotNet.SourceUri": "[parameter('DotNetDownload')]",
    "DotNet.Download": "[JoinPath(variable('Temp.Location'),'NDP472-KB4054530-x86-x64-AllOS-ENU.exe')]",

    "Temp.Location" : "[if(variable('Test.Temp.Location'),Environment('Temp'),parameter('TempLocation'))]",

    "Test.Temp.Location" : "[equal(parameter('TempLocation'),'SIF-Default')]"
  },
  "Register": {
    "ConfigFunction": {
      "Eval": "Invoke-Expression",
      "GetPackage": "Get-Package",
      "TestPath": "Test-Path"
    },
    "Tasks": {
      "RemoveItem": "Remove-Item",
      "StartProcess": "Start-Process",
      "UninstallPackage": "Uninstall-Package"
    }
  },
  "Tasks": {
    "SetupTempLocation": {
      "Type": "EnsurePath",
      "Params": {
        "Exists": ["[variable('Temp.Location')]"]
      }
    },

    "DownloadDotNet": {
      "Type": "DownloadFile",
      "Params": {
        "SourceUri": "[variable('DotNet.SourceUri')]",
        "DestinationPath": "[variable('DotNet.Download')]"
      },
      "Skip": "[or(variable('Check.DotNet'),TestPath(variable('DotNet.Download')))]"
    },
    "InstallDotNet": {
      "Type": "StartProcess",
      "Params": {
        "FilePath": "[variable('DotNet.Download')]",
        "ArgumentList": ["/q", "/norestart"],
        "Wait": true
      },
      "Skip": "[variable('Check.DotNet')]"
    },
    "CleanArtifacts": {
      "Type": "RemoveItem",
      "Params": {
        "LiteralPath": [
          "[variable('DotNet.Download')]"
        ],
        "Recurse": true,
        "ErrorAction": "SilentlyContinue"
      }
    }
  }
}
